name: Test Server Health Status Page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start PHP Server
        run: |
          php -S localhost:8000 -t . &

      - name: Run Curl to test endpoint
        run: |
          curl -sS http://localhost:8000/index.php | tee result.json

      - name: Validate response
        run: php .github/bin/test.php

  matrix-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Matrix for different operating systems with latest PHP version
          - os: ubuntu-latest
            php-version: 'latest'
          - os: macos-latest
            php-version: 'latest'
          - os: windows-latest
            php-version: 'latest'

          # Matrix for different PHP versions on Ubuntu
          - os: ubuntu-latest
            php-version: '7.4'
          - os: ubuntu-latest
            php-version: '8.0'
          - os: ubuntu-latest
            php-version: '8.1'
          - os: ubuntu-latest
            php-version: '8.2'
          - os: ubuntu-latest
            php-version: '8.3'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Start PHP Server
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          php -S localhost:8000 -t . &

      - name: Run Curl to test endpoint
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl localhost:8000
          curl -sS http://localhost:8000/index.php | tee result.json

      - name: Start PHP server and Run Curl to test endpoint
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          php -S localhost:8000 -t . &
          curl -sS http://localhost:8000/index.php | tee result.json

      - name: Validate response
        run: php .github/bin/test.php
