name: Test Server Health Status Page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start PHP Server
        run: |
          php -S localhost:8000 -t . &

      - name: Run Curl to test endpoint
        run: |
          curl -sS http://localhost:8000/index.php | tee result.json

      - name: Validate response
        run: php .github/bin/test.php

  auth-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start PHP Server
        env:
          APP_AUTH_TOKEN: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08' # sha256('test')
        run: |
          php -S localhost:8000 -t . &

      - name: Run Curl to test endpoint
        run: |
          curl -sS http://localhost:8000/index.php | tee unauth-result.json
          curl -sS -H "Authorization: Bearer wrong" http://localhost:8000/index.php | tee wrong-bearer-result.json
          curl -sS -H "Authorization: Bearer test" http://localhost:8000/index.php | tee bearer-result.json
          curl -sS http://localhost:8000/index.php?token=wrong | tee wrong-token-result.json
          curl -sS http://localhost:8000/index.php?token=test | tee token-result.json

      - name: Validate responses
        run: |
          if ! grep -q "Unauthorized access" unauth-result.json; then
              echo "Unauthorized access test failed"
              exit 1
          fi

          if ! grep -q "Unauthorized access" wrong-bearer-result.json; then
              echo "Wrong Bearer token test failed"
              exit 1
          fi

          if ! grep -q "Unauthorized access" wrong-token-result.json; then
              echo "Wrong Token test failed"
              exit 1
          fi

          if grep -q "Unauthorized access" bearer-result.json; then
              echo "Bearer token test failed"
              exit 1
          fi

          if grep -q "Unauthorized access" token-result.json; then
              echo "Token test failed"
              exit 1
          fi

  matrix-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Matrix for different operating systems with latest PHP version
          - os: ubuntu-latest
            php-version: 'latest'
          - os: macos-latest
            php-version: 'latest'
          - os: windows-latest
            php-version: 'latest'

          # Matrix for different PHP versions on Ubuntu
          - os: ubuntu-latest
            php-version: '7.4'
          - os: ubuntu-latest
            php-version: '8.0'
          - os: ubuntu-latest
            php-version: '8.1'
          - os: ubuntu-latest
            php-version: '8.2'
          - os: ubuntu-latest
            php-version: '8.3'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Start PHP Server
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          php -S localhost:8000 -t . &

      - name: Run Curl to test endpoint
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl localhost:8000
          curl -sS http://localhost:8000/index.php | tee result.json

      - name: Start PHP server and Run Curl to test endpoint
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          php -S localhost:8000 -t . &
          curl -sS http://localhost:8000/index.php | tee result.json

      - name: Validate response
        run: php .github/bin/test.php
